-- Add aa_ratio jsonb column for androgenic:anabolic ratio data from literature
-- Educational reference only. Values from rodent bioassays (Vida 1969, Kicman 2008, etc.)
-- and modern in-vitro selectivity for SARMs. Does NOT predict human outcomes.

ALTER TABLE public.compounds ADD COLUMN IF NOT EXISTS aa_ratio jsonb DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_compounds_aa_ratio ON public.compounds USING gin (aa_ratio);

COMMENT ON COLUMN public.compounds.aa_ratio IS 'Historical androgenic:anabolic ratio data from rodent bioassays (1950s–1980s) or modern in-vitro selectivity studies. ALWAYS accompanied by disclaimer. Educational reference only — does NOT predict human outcomes, muscle growth, side effects, or safety. Ratios vary by assay and are NOT reliable for modern compounds.';

-- UPDATE aa_ratio for compounds with verifiable literature values (existing rows only)
-- Compounds without reliable data remain aa_ratio = NULL
-- Exact 'name' matches required. Structure per task spec.

UPDATE public.compounds c SET
  aa_ratio = v.aa_ratio,
  updated_at = NOW()
FROM (VALUES
('Testosterone', '{"anabolic": 1, "androgenic": 1, "ratio": "1:1", "assay": "Reference standard (Hershberger)", "sources": ["Vida 1969"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Testosterone Propionate', '{"anabolic": 1, "androgenic": 1, "ratio": "1:1", "assay": "Reference standard (Hershberger) — same active as Testosterone", "sources": ["Vida 1969"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Testosterone Undecanoate', '{"anabolic": 1, "androgenic": 1, "ratio": "1:1", "assay": "Reference standard (Hershberger) — same active as Testosterone", "sources": ["Vida 1969"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Nandrolone', '{"anabolic": 10, "androgenic": 1, "ratio": "10:1 – 16:1", "assay": "Hershberger rodent bioassay", "sources": ["Vida 1969", "Kicman 2008"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Deca-Durabolin', '{"anabolic": 10, "androgenic": 1, "ratio": "10:1 – 16:1", "assay": "Hershberger rodent bioassay (nandrolone decanoate)", "sources": ["Vida 1969", "Kicman 2008"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Anavar', '{"anabolic": 3, "androgenic": 1, "ratio": "3:1 – 13:1", "assay": "Hershberger rodent bioassay", "sources": ["Vida 1969", "Kicman 2008"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Winstrol', '{"anabolic": 3, "androgenic": 1, "ratio": "3:1 – 30:1", "assay": "Hershberger rodent bioassay", "sources": ["Vida 1969"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Boldenone', '{"anabolic": 2, "androgenic": 1, "ratio": "2:1 – 100:1", "assay": "Hershberger rodent bioassay", "sources": ["Vida 1969"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Equipoise', '{"anabolic": 2, "androgenic": 1, "ratio": "2:1 – 100:1", "assay": "Hershberger rodent bioassay (boldenone undecylenate)", "sources": ["Vida 1969"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Masteron', '{"anabolic": 3, "androgenic": 1, "ratio": "3:1 – 4:1", "assay": "Hershberger rodent bioassay", "sources": ["Vida 1969", "Kicman 2008"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Primobolan', '{"anabolic": 2, "androgenic": 1, "ratio": "2:1 – 3:1", "assay": "Hershberger rodent bioassay", "sources": ["Vida 1969"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Ostarine', '{"anabolic": null, "androgenic": null, "ratio": "~3:1 – 90:1 (in-vitro selectivity)", "assay": "Modern AR transactivation selectivity studies", "sources": ["Dalton 2011", "Miller 2011", "Narayanan 2018"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('LGD-4033', '{"anabolic": null, "androgenic": null, "ratio": ">500:1 (in-vitro selectivity in rats)", "assay": "Modern selectivity studies", "sources": ["Basaria 2013", "Vikingson 2013"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('RAD-140', '{"anabolic": null, "androgenic": null, "ratio": "~90:1 (preclinical selectivity)", "assay": "Modern in-vitro/in-vivo selectivity", "sources": ["Miller 2011"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('Andarine', '{"anabolic": null, "androgenic": null, "ratio": "~3:1 – 10:1 (in-vitro)", "assay": "Modern selectivity studies", "sources": ["Yin 2003"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb),
('S-4', '{"anabolic": null, "androgenic": null, "ratio": "~3:1 – 10:1 (in-vitro)", "assay": "Modern selectivity studies (Andarine)", "sources": ["Yin 2003"], "disclaimer": "Historical rodent bioassay data (1950s–1980s) or modern in-vitro selectivity only. Does NOT predict real human muscle growth, side effects, metabolism, dose-response, aromatization, or safety. Ratios vary widely by assay method and are NOT reliable for modern compounds like SARMs. Individual variability is extreme. Educational reference only — not a ranking, recommendation, or prediction of outcomes."}'::jsonb)
) AS v(name, aa_ratio)
WHERE c.name = v.name;

-- Verification query (run after migration):
-- SELECT name, aa_ratio FROM public.compounds WHERE aa_ratio IS NOT NULL ORDER BY name;
